sudo: required
language: ruby
services:
- postgresql
- mysql
- docker
branches:
  only:
  - qa
  - nypl-dams-prod
rvm:
- 2.6.5
cache: bundler
before_script:
- psql -c 'create database fedora_ingest_rails_test;' -U postgres
- mysql -uroot -e 'CREATE DATABASE ami_filestore_test; CREATE DATABASE image_filestore_test'
- mysql -uroot ami_filestore_test < ./db/resources/ami_filestore_schema.sql
- mysql -uroot image_filestore_test < ./db/resources/image_filestore_schema.sql
script:
- gem update --system
- gem install bundler -v '2.2.15'
- rvm use 2.6.5 do bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
- rvm use 2.6.5 do bundle exec rspec
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
- provisioning/travis_ci_and_cd/ecs_deploy.sh

env:
  global:
  - secure: dkp51DjV4/olD9PlhiongB8ov/xE6cYqmOQGYWgzVxBS46dmKqxZPxcLK0LllMmVRKkDPm4WOnwMlxGFh10SX/gljrw3Y+GnZ/z/vMbhLwJ/mACG8WIzNu9vVktfjmnslW03WgP7B/pEgaKewlXeRMz8FNZ/YLRuH/MDUPJ6WUBAfiapolfNEP3NwgALebudt80OnXylZCPFS+ITkDjHhCt4g2DeLOV8Gpt7kO0pfca4ZRWpbZt1sUFNLBZFKc9avJkdPGQEBfY+UoWT9Bvu5xEp7KB0ldQwahxJosf1TxyGHczN9qz7ipD0RGti1Tothmwsy2OeeRkl/ekFeBtLLJr6RXR2nZpAAwd4BVhlJ5rDc43cJ6vzBy3XNdjWB9Gbt4AUfmpIBFttI7UBrrZHLjXZwdEdUGjkZPXaerI2wLrf9fTezShKV+6oC68XtR4oMMWZK3jaXS9Ki01WY84fIAfr0fYptYEW/AZrVudD0kk3wtqyIDx0dNc2aBJZrsDtHcmn/HZGWkMVwRooPs7epFT+iFi/ATy6MysqUWwWyq80jsTSVuyrUDfyLQsZU/J/Z1c6dzbAguvk81aluAFyjoKXK0OpNNoLMVCD6QQwqx9Aq/oT+fCGtCnwOy3OTP0hp6GxKMQZCzlyiAKsxEWjaUkiQOlK5biTMtRbVCTVi1E= # AWS_ACCESS_KEY_ID_QA_NEW 10/24/2023
  - secure: h4in26YtYN/zd6SzRpjEcwsf/idZofkwBfkWumTbaWsYnzUV6HI1BmpTSntnNl2cEN8RxZScxknCPXUY7z4zyt1gJ1uf+10GXWbmRaeC9fZzSKm7OHPIYVIRyVkRMPP4jwIun9Rp/0kPMZ2i/0B8+n9e6aLue4XY37vRSfNbkhAjodTnN60xskzUMx8XLcwPhWjBtwzIz5PPveqMXWxQV0Bw6lgqow8rlq46gr+ojSQ/McDefWpalBzCufEZLBH8P5mNbniKjVLsNEi7Qfn6cXyxKAVuwn2uw1jncZuIyS9vbEduQJbTYDYmXdiHsNDbMeLu9bpaAN4M4RHAGEUXhuiv0i9Pbyv0VkCtcZnte7AnkJHgC+eWzOG6VCGlZk1Cbqzo3AiA+UySDZVRw6E5qvNIxaehe6T4Ddz0juOJT0Tg+48d7ve33XNhCaQMPaiYqSspOr/t5MgkSPbcHAQClaHZydhYlYdpJiLJjFJnZ2uA1yUtCUGfwvawn74fi0qFzlN5oyUtqFRA5TFwKLnfZ7ebdl8fgk9/60t8Zbmjw3gbTejqcEC2LBClfCPTyugF9dLsyX4l8UuuBTTaHKX6R6+2FKrQ/Uda+VpZelYIWFfHjS2zCy0vNnKBy+cTHe1ezgooDKaRi5guic4unIf4i1vf5MVvqdEV8BL/4GVwEos= # AWS_SECRET_ACCESS_KEY_QA_NEW 10/24/2023
  - secure: "IHuxu2nGjWnAYVvVwvoYzAIizogtGS8cOo9GXeK/izRDSGZEo0LL+LHndMpyTl4sIWlY/50veXSAJsbJAIE2nv2a3xavroU+FBAZd0T9iVJt57JYS2B1sGJoAo4wRtxYkoyRkg5JbZ2tBPwhtxvpuBadOd11b1nM7mqqOjrF9nYdwPeH/6LoUPMxOZis0johPtVg7hb/+GjTSLQDFdf8l6hSzAN+wyYqqL5ewdc8nQBKDlTCNly0Ig1lUZ7+tREYQTJ4V5cDOkc4LAy+z8tew+YVNJ8ZOVFKdEnbwd0VzTxttkC1kDpIls706fNpa44RzuvPaml7IXQJ/g/BNbCPKxLLulnama0XNpoBmUuVhhuXu7AUyLfGWr/lutYN38uS891nMtDU6rixqY11n6hV2wQYhV/VGfqdNYlzuXfJBrQMuE0TuON3HLZ1Yr5faupUuXt0zvrSW+aFznBoB+e0yJFPf90BQ5a3onpdSj18mMH4EALjtHYVcXWsvFDx04Ub503kX8POjxFPzZ1Ocls4JH4YnpKoXH4bDVneS0fGhQ3pT0eRQD8ssFwWQzHt5bv7TCHEokdI4oDmyfetqbRlxVr0tusJlSkj/4tC2ET8o+pfZxn9VRIyONjOt1xrdSyOiC0BJv52WD1/452Jyv4sHCcsKpHKkg/TY91wKi9/IUg=" # AWS_ACCESS_KEY_ID_PRODUCTION_NEW 11/02/2023
  - secure: "oKbK1zNQMUPOWMsddb/TB2A8PHjrc8s00R6z9oJqtsEnX1YVHEzsZjIRsWhCaNz6wuumrg9Dl1n5YYu71libKDhq2AeOx1f1J203nns48oaaGJnnXRqcT1I9w/PN7FB7cHldRmijvYTXgYVNkYz9MAg8VSLsw3nslGyzvK93DozZNcF+G70RWDr6FazHta3FIFbhZNsktmPlCcCITe4ik0M97Xbchwr3chnpcMmRrr+Ph47yqGsOeMHUxf4wjlF34aZpNjTsxKI2YRTAw9X+S1X6/FG+9eKe0DGUvap8OjVYRpO7bC5B/P1/y/yGM1P+bIB0hZ12Qtx18iAk2SWdzK899L4gtw6WuuovByjbOohAdAoyr32w2Qj9n1ms0ZWaa66nQ+dJEEuMmFTpQ9AlXbfkI7by+G8YYnu5IC9HX1RtYQOUkXkwpoEG7eLXNqrwsPh0/SaijodhjO90faCb5Gag9FMOPFWw0VktE/s/5/88JqvUH4JLzDBvxoLyqXAAL0CVkhL2R3xwYikdQjBfii7ZyXytQ0sm7lpyqvIG7elJSOc7PRSWqWJJ7GTgUSAQdfldv2On2Mbux1ET2p6QC8I6KXDNSM/bTvRFI2Hl9OZC5z1F91gTg386QIBcNU6263Zh7+IHE9nR/MYMkPnKLvqLZ1Rn+SA2T9Ez+QT4/DU=" # AWS_SECRET_ACCESS_KEY_PRODUCTION_NEW 11/02/2023
  - REMOTE_IMAGE_URL_QA_NEW=685731035297.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
  - REMOTE_IMAGE_URL_PRODUCTION_NEW=557492996044.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
