sudo: required
language: ruby
services:
- postgresql
- mysql
- docker
branches:
  only:
  - qa
  - nypl-dams-prod
before_install:
  - gem update --system 3.2.3
  - gem install bundler -v '2.2.15'
rvm:
- 2.6.5
cache: bundler
before_script:
- psql -c 'create database fedora_ingest_rails_test;' -U postgres
- mysql -uroot -e 'CREATE DATABASE ami_filestore_test; CREATE DATABASE image_filestore_test'
- mysql -uroot ami_filestore_test < ./db/resources/ami_filestore_schema.sql
- mysql -uroot image_filestore_test < ./db/resources/image_filestore_schema.sql
script:
- bundle exec rspec
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
- provisioning/travis_ci_and_cd/ecs_deploy.sh

env:
  global:
  - secure: "dR6Bj2KjGeV/pHClVV8MLbIAqwsgja+ge0ZCveGeutuhpmImhlOSWJ2JaKmRIv4OJE23HFzTGam5gHJHWPjidLETNnBg6ZLcCG12tZBjDo4ZTshD4Q2PginE2grSvvzJeCx1vXLkttFEJN/nujGIEHmve/RjHlY/9Q5eGcgoWj39fn+zJUyFowxWyxAHwd77g8vtfWK19FBvc0wKXrCOk+n74ev1w6J3jVvghEglF7Da6ANFsqOLGJmIQF1XKoY0/eXT5VnYdnYHMIAEfBsXm0Fts4O36yPHgwQ8ZKYwYRqarqmKh2iwiuCeSrxuJmyqaQDANX0n9eKPhX993FrTSPZVNS6a9yylFRblkSjxWis7cuJLgZhTZc17JOLDraPCdAWUE1T1ALfn246B1OEl5Hz9/lXUVdQqx06+VD/aEYBUEy/hAMvS6HTtGf4bPjFx0CXLRgtky24/yEK3BAFRsMKm/Ke3fPnvvzy4l1xEAirWiHx5o45B3H4pvlWpAQIj4Jh6a/Za9WdCQmr04t5l3pz1Vstph7atwBFl29d+dKAlp6/EBtEddX2nhbGRBHbdRmgMTNLku16HTLjF6MPbD3h6jQfjcb6wYr0n4c0tcDtDpZWo6EBQBCPUF6HoDRPervbmAoIWWkSOHM7PbUpTf7hzdrfj0OaCdILysyI+n1M=" # AWS_ACCESS_KEY_ID_QA_NEW nypl-dams-dev 20240130
  - secure: "r4M70lktU2B24G9vhpBGuYoqZaWf8JxgIDUAz71Wqk0ISyTtn+eef9QLA2YEt7b3TjBEJsc63HYA0k5P+Mfegn0+CO2CG+OoMvBsSj5ingOGwFKFAjTIE7mWPDSHVoYFfpXPzIxQ5T6PrKPu8Zi7ONmwo5f20TeM8FEuVU1qDrx1D+9GRaUi/tCig8WSr0X3/y+9m4IcuTP8MkJAeqSfVq9hXdnrlE4vLUHPuXeTcKd1rqRoC3iFgsAV4LpVwHEVEKUzZ41l3XwMzjoCrmmJvgHwHBhmETKGFL33SfZqfRY1N2TCj08kwcQRJ7szqLLVb+z3OZ1/zIyCDd8JjTssYLdZuHjtb6dxN7zMXuXfouguO1C64OzUicirVDFcNCuWEZJn14yMk0zUh6WFOwavaocgxfyWA7dJyoEZkkozSir+Tn8dcSsOIQ3ukdBVGrBaP3c3cS5hi/6G9pvnPLwYAjrda+a6Zp4OysMb4pjtPokVVgexyZIZjC7cB/JaA0VrU9z9vaNx+wlVbhKzGUbkM6xtjSvmEMQGzfKofw0Rr4pt/n1j/qccvchS1KXtwqefIAWQN5hScEg0p/KX1RrZHDiP1G01Oszr345AbpemtND6D3CJ3eCIjPGLb1MT+nBWLkqwn7Y8fpI4+ePFNezxZSawy3BltmfbxrFd9kxlarQ=" # AWS_SECRET_ACCESS_KEY_QA_NEW nypl-dams-dev 20240130
  - secure: "iGXdWk2XeWOwRau8mwpdYq3WB2XZ78F3yrgU65yHGg9H5kb2XHeuoHpiBXgDANnIb21gMl3HlXA+cO0bmoHnBAs3u9t9IVu3O+w7zdaeqI6C30ntv5MuYulqPc+AjZCfhj9UR26CZnovrNzmozMCvekI+giibhP+KsGiAEdaD05icgUIItEEXr9g//CUFNEpdwzO9wwTULTSMSboPyGsQ794CpuyKHGLf6hPrpdcjA3nUVhVCnP7ZCF66+29+ElO3D6f4KcdpajIAiKSUTn1FHYW/MHtRjpdJ1lzo+Z1qm+S9tLp71xIkhp6vkq/sXigpn3weZZ22TNZU3MY+X10pz8017HHPnOVTiVzr6t9htsJavUY4/INZVfqIaEnntmllkjzMaOSUqgtWLA8zqe0DrW6anb37r+Y4txJm8MC/sIEaJflMVPJ6KRmVluISRJ78slT3l3Y6qOg4cdKQbE5iNCE/aiGQMCh9jlrLIncJHXiRcm56mZEXhoamsR7UgEVUtqr+Bqj4m83TUP+xbdyNGHz9x/qagLkF1CJRQ7NRnNrrBNbQ628Uz8kom8OaC57xE/+qcaIXk90dvGxPNPemZmg72SQHJ1ZMRC6kAMXoKaUiIsZg5lbfbgogxXrwGWiNVtxgUHXuFL7KprkuVkWQZT9l6NTAsdpy/8WrgbfxCg=" # AWS_ACCESS_KEY_ID_PRODUCTION_NEW nypl-dams-prod 20240130
  - secure: "R4sAdZVzIm0AxWNXTvm2xxpubm+QM1oDZsFVWcRacuRo3zLj0+nXmmPs+rA+QKu0LbfVATGI4Scp7r+f/b1ZUSuoBDdtetBJYp3UGyrLXqlMvTsnntbV6Ng5yFK4eKuclV4M+5HK/RNLSYWjvx/gDzvKbaXQ+sOMtp/5uBqeFI4qGmkj8NXCGLD4ao0sYGSJ3WfqkMV/HXCt6wo9LO01pxqnbMlhIXLXSdDYro4GjSVT6Jy9SNadV4QAsf60Xy2StLqqdqGEw/2GAEV74RLl1xY+BuPciMd5jaINDNRutgRBGg69Wkk/HCuf1M3v44/chc3McHD2DDyBhaTqCApsQ3b50UjQ7+4b9vrzWlC1uL2sV7XmubLngELTAMvpL3blEyyKGg0ELORXGhaR9E6iaQRmYnqfKImfXiyabit76sM+o1qQ15zyjgYLNsO5ovJhAgYKT8eJJzy8ncIT/wT3N8WIfg9ajW59ZVWG3kIxyKRNrHoaApcpawe2gsQIrXz7cAqsunpDJhAN1eFSdejDCbqFySq81r271NPsA5P80NfiiEQXCz0FgwxnDVwmQH7jaWx7g15i1ohLveQMisHfnZ023MFHr8W8UMpq/IyhllyCcAxny6IpSJH+q7inVdSZYMcbLXQ7a7TvTWD2r5JUcHvNuu9vl61cNCkHMceadNU=" # AWS_SECRET_ACCESS_KEY_PRODUCTION_NEW nypl-dams-prod 20240130
  - REMOTE_IMAGE_URL_QA_NEW=685731035297.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
  - REMOTE_IMAGE_URL_PRODUCTION_NEW=557492996044.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
