dist: jammy
sudo: required
language: ruby
rvm:
  - 3.3.3
services:
- postgresql
- mysql
- docker
branches:
  only:
  - qa
  - nypl-dams-prod
before_install:
  - gem update --system '3.3.22'
  - gem install bundler -v '2.5.18'
cache: bundler
before_script:
- psql -c 'create database fedora_ingest_rails_test;' -U postgres
- mysql -uroot -e 'CREATE DATABASE ami_filestore_test; CREATE DATABASE image_filestore_test'
- mysql -uroot ami_filestore_test < ./db/resources/ami_filestore_schema.sql
- mysql -uroot image_filestore_test < ./db/resources/image_filestore_schema.sql
script:
- bundle exec rspec
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
- provisioning/travis_ci_and_cd/ecs_deploy.sh

env:
  global:
  - secure: "C1UI9xeqMIgg67LtVXuPdsUZxgDIShPnGY3bP6nk26DOq43xN5wALz6ejc5pHCKAVXION5/A4xPN0li2dzNtNq8phHDZvUm64cxqY3xc87dX9pRw8rBSrLuEE+bfyz/rdiMo68icMEEsn+Ku/7A3cKLfTmUo8nMtHE7D6ECD5HtB/aFHJFQ0ykXqFvkAsovZ/g5eL8pNEbNc9ZcI4/2fISa35GUS8tofD2dg+F1FxLPJ5hk6fp+SxUDGeTxN1+agRBQS390A25QYf0lIKipuf4LZBa99rzjips2UrafvEM0AyH1njbnvfDnkOdOZhygiesf7fZXS7heD96aX7gUQDPyrqBlBicUUWipo6z4RILFWb497KY8CKm0kI2s91HoPD9yQwhjWagq1u3El6rfHmi287ueN0SK8GlbONgjoeE3bwWvkw7Qh+IJvRYguW6fRVwreBg8gPhLhmVfu9p1kG0Rqxu6M9WeAtn0Wnl7bU2+jjyNejwRKODFotJjrAQ/qn1clHShEIDFb5HuMd2xdgFleV5VqUoVIZFpj85zISCwfptoob8gt3Tk9NDvIwaKWfq9Tknwyaab+hidLljcv8fygEn5A65VMUid9bucuherTTzbgalZeHl/2Pbkdakih8Cg5L3beH06pWt2jUQmiZDOMRot88Uz/+WsuPZU6/eM=" # AWS_ACCESS_KEY_ID_QA nypl-dams-dev 2024-09-09
  - secure: "EJvfWWDRlbef26tVm/yCTGubod2F961C3sKmRBm2VQOjFRnWJXV53UYLZdqmFqzKoBbqS7EnKAKcSaNF2oN5wwLc8gCwdD6yv24AiI8dbDrKE3sdY1IUIgq+zUyB8ANs5ckWrBXwUWZ6DUcp68pffOeUsQq5HYGs2c45T4pZJ4/lsVNQ228CIShkA+elKvMS2o7u9on1ZzHe5KqvPlyjBvW9wS38zN/d2cE6qBKjvkBX8ti3CAGiVUykJ0nyk4ifLtJxuWRd+krnyvnXs045dDgPY0Znj2wxa6jpJo4LbyAN3T2/JUyXk45DT3o0g/mHMlhJnql41Ke4IrS4FjqWyCgxy7CbFTWMkyiIw+m6MLuJ1bArKADVxmMY46Hn+/JOLAzhXu5MKoYrCuT1k2sHs/bp71xGNazXDeHStJhc/h4VOM54BHeOAzTemXOAO6Wgt3htYZVkgBnUeia4UEySEnfdy/NqWLI1AYwRYFhgHazo+vqZSFc3qgdTRcNa8Lpc0Agbw070VDhS4apIwaeiiy/4ierykWZUGku6p68I6j1TS712HjDOxB/alyJrQ+rfIOqWC10V6puHxQ44KtQsVdgBZ029BUH7kYbP5tnk+bXrmoOx2MvTaqaDeY0eUOYls9e4Iz8/mII3y+g+4mZHMkXlv0KMdHBMzNbtvUiZdsc=" # AWS_SECRET_ACCESS_KEY_QA nypl-dams-dev 2024-09-09
  - secure: "q2+xINZHpYbGO8GNd9B9EV3e7GxldG1Z+GSPsrqah/IHf18S4z75JP8prs+Mbw/83HTzF/k8B9E0uvdNu0SgGlL4qBSUpm2bF9Ua6VAcGMjcwCyYspDR5IMFwhKMKeLqcI+rd5IPeJshxuNdcu/1fRRdzLSpdb7QhhRy5B/7yMH8Z0e3nYerSjp5FpRYE0HzgvDAyDf/aG/sOufwlGqI3HI0bYRrXKbi5YUOQjO6msmhhQzOcLFjv0ofq0OwuPjBYBg5tmIwp13IP20qgaU4pbsevgMrtYtGcy+wmUQs+KHUcHzAvd5TVlI473vhrt46seVFMQn/89aluQ4pz/rxM51ti9BgRbswLgROJNct44zpqHHUoeYLvGlD26XEgpm815M/dymtBdAGAcP4oF7JrOMWRyo8pAIT2CBZ/Lxv8fjjjPvjcAcDh+TecvVaZm7E+qm2ioIJP6ZgWX4PADlH4i0ZQe9M4ElDCt/rv+NqomOtoVUe1q7ldCUHgqp7mAMULu9EztxX3WbR+zAD+3wAVHKJLFvdr59D0lWe5tHaLbx1/Lu2uRl6UKJCI3zOjV7a4S2UayB6qre3rHbr5nIJpFIg1ITgEjR9qMG3qYnj65CzpdCr+hNGo0+uCxjpn10O/KW9wN5XL0spbnf5+mqjcy1LBLSu+xNDdWlRyljaTRA=" # AWS_ACCESS_KEY_ID_PRODUCTION nypl-dams-prod 2024-09-09
  - secure: "Dqtnm9JB/LnFSlOKFEpinlkw6tIR0H1Zxsd/bzgHQnepl2GGlwr0IM4HkUdk/vhZJHNbQMhquQRNh0zyLwNrtVBU/WdgdhCm5tbSZ8TA6KVgDtgtGlJuB2gN7wt92uQtiH3oRan4ASfK5VeKo/W0L5MYzaslFE64tPpe7ZJScPOPnGTIJrNJXK3ecpaBXiAuajRZTdMsXv4WH1o6UqAi5LlsK3oPo24eGx+Cb90LxIv9SEvcHAaGFJ6wHrMcvtmP/W+lXSVYdTfeN47FXamJmy0+LdWPo2+6kEA3kaXngFNoqys9lkyK46/8TZ2bFNZtvjzspuDlk7aMTXogSBGWUQsQVJcQS85dowrd8E0b0Kgf8bJ+iY9nnIx+4+uLk2+sHNTzlLjC8sXzTo4lMkNSX56FXjKYm+CYKvekM3H4lwNvM6HDhgqIKpNL9OiuhXV/4Fq2YmU10F9TSI35nsm/TZu6bYYBioHekkkOfta0nbXu9pJm8aKwEIgT5GrbqYik5ou2GIZjeRGjeQBHfhbhB9JwJeFAz9+TnBPrcqt+ftRBiKVw6LgebOlt55JCoW8wGksvyETlxpZYI777Z62xHvq8Q5bhxQE5+mT1ZaU6DraVNrPNIybkqkcHf3JUynAlWqdgMIdAZBxbdAax29IDDDO9Aa/Hh+G32h4PemDZ7cs=" # AWS_SECRET_ACCESS_KEY_PRODUCTION nypl-dams-prod 2024-09-09
  - REMOTE_IMAGE_URL_QA_NEW=685731035297.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
  - REMOTE_IMAGE_URL_PRODUCTION_NEW=557492996044.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
