sudo: required
language: ruby
services:
- postgresql
- mysql
- docker
rvm:
- 2.6.5
cache: bundler
before_script:
- psql -c 'create database fedora_ingest_rails_test;' -U postgres
- mysql -uroot -e 'CREATE DATABASE ami_filestore_test; CREATE DATABASE image_filestore_test'
- mysql -uroot ami_filestore_test < ./db/resources/ami_filestore_schema.sql
- mysql -uroot image_filestore_test < ./db/resources/image_filestore_schema.sql
script:
- bundle exec rspec
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
- provisioning/travis_ci_and_cd/ecs_deploy.sh
env:
  global:
  - secure: MuWkKDgrYbyKGzRj4Z6cyIwk39NsIfkZT0wbC9sB6EOWHbKHmH0aq8t4YkbegO9NoWJOuQQPn7gKKkGFnjpr6v6UfQ0gWAFEsiYU7pr2l6/hecFi0U9DGo3V2Ha9T82wxP55yVnsuRhdo0Up2xgqXVqxTLv+oG684SYm2Qq6/RiC5i3eM89PtS6SeBjO+/1VLJWWd+NUHSZSveCUuckDXqspXYZ6MYvewImiEB9W3SUs3qsw05fsmt5yVSVer5aO6pg/pjkgN/3DYaFTU5sJejhgPYQWTZIXHJJNxefD2nic+NdrJYhPDW+/QN4XGcHLXRsymTYbJ5QXdz6Kp1Z83VmMgv6VruPiESuVgylXaiVMAkZ6cRiGZsvRT5Ax8dAP6cfVhbwMg6vJ5xxFoMHNCz34ED0Y9T/Ckbn7hvs20XYNFWuQdeT1K7i6lnSgru0p9siFNbrPm30VIQBI3z5dBXvKZ7N3QPOaEbEVXpuqInYbJWUZRPTG+OKgUrRA2HBfMCsLjFPa767l/ISeY/lZMx2v3DwhtTbzNGDTPmdw7pzrspJJvSfjUTX/a1HT6PhWulfkP8FiwkjibUtJPpQeqnGfuhdcu9BN9vB0JskX6Wx+v1eBcNBIxdfH9+MNjjknbPS+lmlVsRH2vB3YNjRGq8Uv26LOXHz0/zqA1ve1bgg=
  - secure: oFSIw5Zz96lvPfVQr5djLdQJqdYUxLikrUXCHchfgOv0UbrEBDPSJTD+yynUKu6IDcy+aPjYV7Tb7kVWofkXMAiKwN+gtr3OM8cTxoxC0PGRVTwlP7D1lHCXlqQ/UCI9AMcMGo3QjDchVVgUzImM3QHpNPkNMPwyXjA0j/EnX0g/jAw0I7o5G99phBqZytkTnsxOC/9VJX5+g7Hect5n2IdRfCiuQK/VOxbDXkguUJ01cd6ENdjIV4Wy/UbYPIqjenRJj4PSMPmrsQxl+nP3RcvEGK7XOoPNZ7xc3YUaLZOAh6LDUh9MqesK+r2bGOU4v7Wg7unfnSzvpQJyAlyayjDWl61vJ7JfSrnt2HSh+rcpfWX9mKYORNOo49/Kj1Of8yH399w9mqlm8/DQdLKJ4KUyjb35cO5p60vx9OKVq9DQi5fJfSdMD2PsVz4AUJvGhntImH1Rc3gzDeu5vT8MmAZao5pQMvBNF/m125BqMW+iHwO7hMcJyB9k/X2Gi6aj7A957bc+nNICcT5XIvvWxINWxPfBcYddyGp0beiRG6qHEOji232sBplKZn5ufx0ZJe4TIzFb/fpd2PqJp1XZijJ2yM5/fc8+N952bPqPCSUCKDKToZcBLzba/GFEx9nR01uIX7Ch6H94kFWXo2ikqDGHT/WxBO+PpJdtQlWHHs4=
