dist: xenial
sudo: required
language: ruby
services:
- postgresql
- mysql
- docker
branches:
  only:
  - qa
  - nypl-dams-prod
before_install:
  - gem update --system 3.2.3
  - gem install bundler -v '2.2.15'
rvm:
- 2.6.5
cache: bundler
before_script:
- psql -c 'create database fedora_ingest_rails_test;' -U postgres
- mysql -uroot -e 'CREATE DATABASE ami_filestore_test; CREATE DATABASE image_filestore_test'
- mysql -uroot ami_filestore_test < ./db/resources/ami_filestore_schema.sql
- mysql -uroot image_filestore_test < ./db/resources/image_filestore_schema.sql
script:
- bundle exec rspec
after_success:
- provisioning/travis_ci_and_cd/build_and_push_to_ecr.sh
- provisioning/travis_ci_and_cd/ecs_deploy.sh

env:
  global:
  - secure: "lXSUvGzg2IVV40a96gZ2b5yHh/y2wKP0iGKh5zfgTEZiq5RjiyLsSXnJGoxGXP7JyH//TUjQgKWhrAGZyHfzVXmtpiVkMiGe7Im+78GQl4JTszVng2YcoTOxdegI2Nnnta2WoQVupCR7vBMqOrzOIzSDJkM0rtz+V9rYfFnevTqrRf7pv0UrT1ZNdKKz6BZ1vzliWgmq2RB2LT5XgJPg+FRU8E5Tg8NMRRcWXcFrT1/W0w21oVHNMMeL6JSQPXr034ueJ7X/6GLYqdLQ+25GnY8hMTO4PrOpXWzvkqqdubZVdhaKfVxf63hACg5vaNSUY2R7DyBUFPUfZCOQbHeAU752SgQNjnS/fNDBeyI/y9f6SmuxPezRiKJcWZek6E7aheCFft4XSlkt7SmICTMkEH9fnnh2x4ZMQ46Ij7W6+vQRmHzH/rCsGGQZwLwYVwh/sEloP0zviJo8YCEHb5bW2/UmK7vmfCvEROWNYnFCNsJcM1mTZtyqTrVqOsP07dy6Flqqf0LwOQnDxIcU1Fgm77PMynQrzrNhIeHQOkLKlDYDoxVsK+Dylsw9jEE2oOMZsg3mzlrVRBl38GjBQQ00FIvsQHMnHN0/YHvdFPf+NGlhnb2ScIhYLXRcd1W2z0pFWu1BkJw4lgnA4ol9+S9xIX9PbgwXy9/YrK/cUW+DbxY=" # AWS_ACCESS_KEY_ID_QA_NEW nypl-dams-dev 20240131
  - secure: "gnU8D35Dva4et7ZI9dBEa/2RbMGhuXg3Iupk7a7F2if0T5RP8cm3UzcMJKckn8pjMYx+oy7sYwP6y7jXV4g3TeaGahHzLLR5BagylnOCWlXvRSEzHKFrPNkXmP82l3Czich5sVIIiQaKlJzxMfBmUjfLhZ6badaHu1d20tPYV/7At9puhARNnqiNMvEs/iJ+AasUChJCL5XN9yMqGKInHCkrH4bGVAOQPD0hwvPBMQjaTS+P7RTvZ+4cULEBEuM19w5XzEJZhXEsy8SGlUf7yVuyf2XnSsf6C/CfrKJbGi9QkmUoT+pZTBPCnI6c+xGFMs1J+zpIGoMx2AgbV2Y8QzmWkA9EeWcK2UsWmtSlSw0Bu+FrTRqLKCf2NkZoG4qD64dNqeZ2SChoPSi+NM9tyfBYoGo4Sgdj98mhh9aspoq6V0EjVrBpwdj66Uv7iqBYYYS6Hd7nIxDH0JZoLUl3qY40mmrO079mm0wzKJDBZU0LR/VmgHHOdzCLzQ3AwgrICZpzydYPwEVzyyN1FKc0Kg3mbqAVWNyqMlFCnbObtdH5oyYdez6LwHCax9kvquOWlTMotNfuz+8cNE/PDKtll13WiraGbU1BSE0S0kCE2YWvPZxXdQUMJyDb7f3MWc7gohIHCd428sWaoTN+TUq1MZrYUwPv733ikcYY5QGRKHA=" # AWS_SECRET_ACCESS_KEY_QA_NEW nypl-dams-dev 20240131
  - secure: "r5ygjytnMKzRx4el29LvX4rBo6npAliXmpUJWhf34mZvl+W2sySiJD+T4iygHBh3psrbjs7Co6Beh1IVpNGTeDcuf8SAkCbhnnNlvwFbdTdmzkN7x/e60oBQA9BWmRsgpeVV0tGh241GM8bX48Z1OXlVUGjQdFZecriJZ4KwEzbJ37oVAdhOFU1tCu07vrgH40uJ2xAqdNgzgK5eGbiZUk77z6hoXMTxTVNhE02vyyDeYZsisTf33GSKKFStOgzrinv0+wHvqsfhgQA3bIp+WbzS3mhptpn0Zj93S3topeLtZehCY9z1NK2gZ+LsBVz4qcPMzjbcwey/0Y75Zv6RhBhY9ZGFWRM2aaVCZjijCv+pGEE4A4eENdN5PRp7xHKqbsIxYgMXYj4M2TUWSM0nWETS9WMEwAeuUZMmRrIH87n4Ytfz0bW+qDfBM0/03rypNFQXLEqvbXJCeQil/XbJPQBOeWkO3ZRLsTF8Fmqdk+4URCEYGPbXQ5Yl2bHzz6yf/rvZUNUygYE0gS/e0VGhN+IX/IQPznmzPxEfscx31T+1d9RWG364X6TdxwcIT/IsJJ6uFoKvDR3DzqGm10Y/OAjG3UiWO8YdfaHBOqrB+i4S1UYXkjrYTI6mXcSREGsfiSVj/bQTNrf3VW9lQ2lKDa2PaH1KAJOBLtSBqxxk2n0=" # AWS_ACCESS_KEY_ID_PRODUCTION_NEW nypl-dams-prod 20240131
  - secure: "BbkvV/1HTU3NSQAT2CQ9nxw+OxNXNK05JAnKMHiW1XoAVInwdLo7NH5MLdfqVTwMQUS3l0+pg8q6XTvgP7w49/gO5epuGyU2k/fyigSCfBt4ZSxBbIYNu2Nc+Y50wE7kLviBQX5QWF8LwqGecv+F/Kg+Rw0Hba1HMG9XXglF9Y1jFTaMEvyp1QDIF9Tj/4JGVZs2efSvwj9LNWAJkc9E+vvo4enCAZg/SIB2IF8jEUaF0FgpVGDSiCP4/WbBX7MqmHQyBbZw2wnWkFjrlph1QGjanCbFUS19Sb7DWJgAhzwjOQtG179AG2fKnQc5KoGi7xi1hbyUO0PX6X1MKmnXDVyZX4aJ3wyYimccR9FFyUQ4TAzxnO90YwWaa7iJJ9EIxCMm9H2SQZF8qYMNWEgayVim4gn4PA720XFik/fhAzAhc2rfHRRAqDt5kzIVP8Qe9aIk3FC4rYAcYWtKl34bKI6Rba/6wvkKcxTAElwxYcAMBmjbrhOG1dlK7/S2jksv3CHBNoq+guVQJPDgxjP6oNCGzlaadh18apDMKTwp+I5Gq7sQUadRnzPKNhscrYFJdwaY4o+S3P3XL6dKjihW2Euyb6sO7g10sC+4ra3gofQV/Et1jOJ523r9FTzyu/JEfdlknIKSYnp6DP8i1Y+FMbNFlU4fn+XLAensugeOKb0=" # AWS_SECRET_ACCESS_KEY_PRODUCTION_NEW nypl-dams-prod 20240131
  - REMOTE_IMAGE_URL_QA_NEW=685731035297.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
  - REMOTE_IMAGE_URL_PRODUCTION_NEW=557492996044.dkr.ecr.us-east-1.amazonaws.com/fedora-ingest
