services:
  webapp:
    network_mode: mynetwork # uncomment for drr integration
    build:
      context: .
      dockerfile: Dockerfile
      target: development
        #platform: linux/arm64 # uncomment for M1 macs
    platform: linux/arm64
    env_file:
      - ./.env
    volumes:
      - '.:/home/app/fedora_ingest_rails'
    ports:
      - '3000:80'
    depends_on:
      - postgres
      - filestore-db
  worker:
    network_mode: mynetwork # uncomment for drr integration
    image: 'fedora_ingest_rails-webapp:latest'
    platform: linux/arm64
    env_file:
      - ./.env
    volumes:
      - '.:/home/app/fedora_ingest_rails'
    entrypoint: /home/app/fedora_ingest_rails/bin/delayed_job run
    depends_on:
      - postgres
      - filestore-db
  filestore-db:
    network_mode: mynetwork # uncomment for drr integration
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
    volumes:
      - ./database-data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  postgres:
    network_mode: mynetwork # uncomment for drr integration
    image: postgres:12-bullseye
    platform: linux/arm64
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432'
