version: '3.4'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env.docker
    volumes:
      - '.:/home/app/fedora_ingest_rails'
    ports:
      - '3001:80'
    depends_on:
      - postgres
      - fedora
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env.docker
    volumes:
      - '.:/home/app/fedora_ingest_rails'
    entrypoint: /home/app/fedora_ingest_rails/bin/delayed_job run
    depends_on:
      - postgres
      - fedora
  postgres:
    image:  postgres:9.4.14
    volumes:
      - ./database-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432'
  fedora:
    build:
      context: ../fedoracommons-3.4.2-dockerized
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
