default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fedora_ingest_rails_development

development_image_filestore:
  adapter: mysql2
  host:     <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_HOST") {'localhost'} %>
  database: <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_NAME") %>
  username: <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_USER") %>
  password: <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_PASSWORD") {nil} %>

development_ami_filestore:
  adapter: mysql2
  host:     <%= ENV.fetch("AMI_FILESTORE_DATABASE_HOST") {'localhost'} %>
  database: <%= ENV.fetch("AMI_FILESTORE_DATABASE_NAME") %>
  username: <%= ENV.fetch("AMI_FILESTORE_DATABASE_USER") %>
  password: <%= ENV.fetch("AMI_FILESTORE_DATABASE_PASSWORD") {nil} %>

test:
  <<: *default
  database: fedora_ingest_rails_test

production:
  <<: *default
  database: fedora_ingest_rails_production
  username: fedora_ingest_rails
  password: <%= ENV['FEDORA_INGEST_RAILS_DATABASE_PASSWORD'] %>
