default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: postgres
  database: fedora_ingest_rails_development
  username: postgres
  password: mypassword

image_filestore:
  adapter: mysql2
  host:     <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_HOST") {'localhost'} %>
  database: <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_NAME") %>
  username: <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_USER") %>
  password: <%= ENV.fetch("IMAGE_FILESTORE_DATABASE_PASSWORD") {nil} %>
  reconnect: true

ami_filestore:
  adapter: mysql2
  host:     <%= ENV.fetch("AMI_FILESTORE_DATABASE_HOST") {'localhost'} %>
  database: <%= ENV.fetch("AMI_FILESTORE_DATABASE_NAME") %>
  username: <%= ENV.fetch("AMI_FILESTORE_DATABASE_USER") %>
  password: <%= ENV.fetch("AMI_FILESTORE_DATABASE_PASSWORD") {nil} %>
  reconnect: true

# The ENV VARs are for Dockerized localhost, the default Procs are for Travis
test:
  <<: *default
  host: <%= ENV.fetch('INGESTOR_TEST_DATABASE_HOST') { '127.0.0.1' } %>
  database: fedora_ingest_rails_test
  username: postgres
  password: mypassword

production:
  <<: *default
  database: fedora_ingest_rails_production
  username: fedora_ingest_rails
  host:  <%= ENV['FEDORA_INGEST_RAILS_DATABASE_HOST'] %>
  password: <%= ENV['FEDORA_INGEST_RAILS_DATABASE_PASSWORD'] %>
