# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# repo = Rubydora.connect :url => 'http://localhost:8080/fedora', :user => 'fedoraAdmin', :password => 'password'
development:
  secret_key_base: 95bfdfa5ad84245fe7031b55a06c125f0621fc514d186c440ea493a630e7f07ed01347d4f485405ade8f184470413ada717bcb6ee32c741c1ae47996f7bac12a
  fedora_url:      <%= ENV['FEDORA_URL'] %>
  fedora_username: <%= ENV['FEDORA_USERNAME'] %>
  fedora_password: <%= ENV['FEDORA_PASSWORD'] %>
  mms_url:         <%= ENV['MMS_URL'] %>
  mms_http_basic_username: <%= ENV['MMS_BASIC_USERNAME'] %>
  mms_http_basic_password: <%= ENV['MMS_BASIC_PASSWORD'] %>
  rels_ext_solr_url: <%= ENV['RELS_EXT_SOLR_URL'] %>

test:
  secret_key_base: dcf6716d56b60a041b72e829d2d9a5382bce4f575544737dd2a924ca166002fb94dcb9e1107058270841998a0d5f12380b3fb0052a2fa3ca50d22852b2d9d031
  fedora_url:      hardwired-to-garbage, don't connect for tests
  fedora_username: hardwired-to-garbage, don't connect for tests
  fedora_password: hardwired-to-garbage, don't connect for tests
  mms_url:         hardwired-to-garbage, don't connect for tests
  mms_http_basic_username: hardwired-to-garbage, don't connect for tests
  mms_http_basic_password: hardwired-to-garbage, don't connect for tests
  rels_ext_solr_url: hardwired-to-garbage, don't connect for tests

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fedora_url:      <%= ENV['FEDORA_URL'] %>
  fedora_username: <%= ENV['FEDORA_USERNAME'] %>
  fedora_password: <%= ENV['FEDORA_PASSWORD'] %>
  mms_url:         <%= ENV['MMS_URL'] %>
  mms_http_basic_username: <%= ENV['MMS_BASIC_USERNAME'] %>
  mms_http_basic_password: <%= ENV['MMS_BASIC_PASSWORD'] %>
  rels_ext_solr_url: <%= ENV['RELS_EXT_SOLR_URL'] %>
