name: Run Tests

on:
  workflow_call:
  push:
  pull_request:
    branches:
      - nypl-dams-prod
      - qa

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .env file
        run: cp .env.example .env

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          # Specify services so we don't need to spin up the delayed job worker
          services:
            - webapp
            - filestore-db
            - postgres

      - name: Initialize database
        run: |
          docker compose exec postgres psql -c 'create database fedora_ingest_rails_test;' -U postgres
          docker compose exec filestore-db mysql -uroot -e 'CREATE DATABASE ami_filestore_test; CREATE DATABASE image_filestore_test'
          docker compose exec filestore-db mysql -uroot ami_filestore_test < ./db/resources/ami_filestore_schema.sql
          docker compose exec filestore-db mysql -uroot image_filestore_test < ./db/resources/image_filestore_schema.sql

      - name: Run Tests
        run: |
          docker compose run webapp /bin/bash -c "cd /home/app/fedora_ingest_rails && bundle exec rspec"
